### PR TITLE
feat: Local doc search added

### LINKED ISSUE #220: How about adding docsearch
How about adding search into the docs. Can be useful as the doc grows

Adding docsearch seems pretty straightforward
https://docusaurus.io/docs/search#using-algolia-docsearch states that open source projects can apply for a free API key and scheduled scraping+indexing.

Here is what I got from a manual indexing
https://neutralinojs-github-io.vercel.app/

### PR DESCRIPTION
**Pull request by viralgupta**
closes #220 
Basic offline search has been added to the documentation using [this plugin](https://github.com/praveenn77/docusaurus-lunr-search).

preview 1
image

preview 2
image

### CODE REVIEW

**Comment by shalithasuranga** [comment]
@viralgupta Could you please resolve merge conflicts? we can merge this soon once you update this PR.. Thanks :tada:

**Comment by viralgupta** [comment]
Hi @shalithasuranga, I have resolved all the conflicts. we can merge this now 😊

**Comment by shalithasuranga** [comment]
Hello. thanks for the update. I tested this PR locally and noticed that the search box is not functioning properly:
image

It always shows "Loading...". Could you please check? thanks :tada:

**Comment by shalithasuranga** [comment]
Ah it worked now, Merging.. Thanks :tada:

**Comment by viralgupta** [comment]
> Ah it worked now, Merging.. Thanks 🎉

The search functionality only works after building the documentation. You can checkout more about it [here](https://github.com/praveenn77/docusaurus-lunr-search) 😊

**Pull request merged**
