### PR TITLE
Updated Twitter link in docusaurus.config.js

### LINKED ISSUE #338: X.com links should be there inplace of twitter links.
There is twitter link in the docusaurus.config.js which are not in the latest trend so that should be changed to X links.

### PR DESCRIPTION
**Pull request by SarthakPaandey**
I have made the changes for twitter link. Fix #338

### CODE REVIEW

**Comment by SarthakPaandey** [comment]
May you please merge it @Avaray  if there is no issue.

**Comment by Avaray** [comment]
> May you please merge it @Avaray if there is no issue.

If I could, I would. I'm just a random person and still have no idea why you tagged me :D

**Comment by SarthakPaandey** [comment]
> > May you please merge it @Avaray if there is no issue.
> 
> If I could, I would. I'm just a random person and still have no idea why you tagged me :D

sorry it just came in @ tagged section really soryy

**Comment by SarthakPaandey** [comment]
I think @shalithasuranga is the right person for contact!

**Review by shalithasuranga — APPROVED** [review]
Thanks so much for your contribution @SarthakPaandey :tada:

**Pull request merged**
