### PR TITLE
added-x-links-inplaceof-twitter

### PR DESCRIPTION
**Pull request by SarthakPaandey**
Fixes issues #338 .
I have added X.com links in place of twitter links.

### CODE REVIEW

**Comment by brakmic** [comment]
@SarthakPaandey ,

You changed a lot more than merely the links. A PR must be precise and as minimal as possible.

**Comment by Avaray** [comment]
@SarthakPaandey I'm not sure if I'm the person who should/can do that.  

Anyway - you formatted the entire document.  
I think you need to revert `indent spaces` from 2 to 4, and use single quotes rather than double-quotes

**Comment by SarthakPaandey** [comment]
Yes i have allowed edits by maintainers.

**Comment by SarthakPaandey** [comment]
Sorry ,working on it.

**Comment by SarthakPaandey** [comment]
Hey @Avaray i have made the changes as you said.

**Pull request closed without merging**
