### PR TITLE
Grammatically updated tech docs

### PR DESCRIPTION
**Pull request by DaanishShaikh**
made small but meaning changes to the docs in various places.

image
image
image
image

### CODE REVIEW

**Comment by DaanishShaikh** [comment]
hi @shalithasuranga can you check out my pull request

**Review by shalithasuranga — APPROVED** [review]
Thanks @DaanishShaikh, these changes look great :tada:

**Comment by DaanishShaikh** [comment]
@shalithasuranga thank you so much!! i am planning to apply for google season of docs, and for that i want to make a lot of technical document contributions. can you tell me is this type of contribution considered a good technical writing contribution? good enough to show in my resume for GSOD? i am a beginner to open source, and am learning to start contributing in code as well. this was my first accepted pull request. any kind of guidance would be much much appreciated!!

**Comment by DaanishShaikh** [comment]
@shalithasuranga thank you so much!
and yes many people have no idea what gsod is, it hasnt been as popular as the gsoc programme, even a 25 yrs experience technical writer i talked to had no idea what gsod was!!
i am learning web development to start contributing in the actual code base that is the gsoc type open source, in a months time i will start contributing to the code base as well!

**Comment by DaanishShaikh** [comment]
@shalithasuranga thank you so much!!

**Pull request merged**
