### PR TITLE
Update `Use Frontend Libraries` article

### PR DESCRIPTION
**Pull request by ernest-rudnicki**
This PR:
-  Moves `Using Frontend Libraries` article to `Getting Started` section.
-  Updates this article with instruction on how to setup `@neutralinojs/lib` package.

It is associated with this issue [Neutralinojs #1069](https://github.com/neutralinojs/neutralinojs/issues/1069).

### Rationale for moving article to `Getting Started` section
In modern web development almost nobody uses vanilla JavaScript to build web apps. The first thing they will be looking for is if neutralinojs supports modern web dev frameworks and instructions on how to set them up. Therefore `Getting Started` section is the most logical place to include this article as it would be the first place developers will start looking for

### CODE REVIEW

**Comment by ernest-rudnicki** [comment]
@shalithasuranga I've updated the article on how to set up a modern framework with importing client library functions from npm package. If you could take a look and give some suggestions on how to improve it that would be great!

**Comment by shalithasuranga** [comment]
Hey @ernest-rudnicki. Thanks for sending this great PR. I've done a few changes to your submission via [this commit](https://github.com/neutralinojs/neutralinojs.github.io/pull/273/commits/ab4f48d82a9196818b63015d0b6e56465c135f27). Could you please double-check and make sure whether those changes doesn't invalidate your changes?

Thanks :)

**Comment by ernest-rudnicki** [comment]
Changes looks good for me, I have added just two small fixes, one with the path so that it matches exactly the one in `zero` template.

Thanks for help!

**Review by shalithasuranga — APPROVED** [review]

**Comment by shalithasuranga** [comment]
Hey @ernest-rudnicki thanks, would you like to display your GitHub name and link on our [committers page](https://neutralino.js.org/docs/contributing/committers)? We often add contributors who do very good contributions to this page :)
Thanks :tada:

**Comment by ernest-rudnicki** [comment]
Yes, that would be great, thank you!

**Pull request merged**
