### PR TITLE
add docsearch

### PR DESCRIPTION
**Pull request by cmgchess**

### CODE REVIEW

**Comment by pathange-s** [comment]
Why did you close this @cmgchess ?

**Comment by cmgchess** [comment]
It's my Algolia account. I accidentally made the PR on upstream.

**Comment by cmgchess** [comment]
if an api key is obtained after applying, adding just this in `docusaurus.config.js` should do

```javascript
    algolia: {
      apiKey: 'seacrhApiKey',
      indexName: 'indexName'
    },
```

**Comment by pathange-s** [comment]
@shalithasuranga can you provide the API key for the same. (if there exists one / consider creating one).
It was a great pain for me when I started off with documentation. Having search features will really help and is required.

**Pull request closed without merging**
