### PR TITLE
Updated Tempalates

### PR DESCRIPTION
**Pull request by skushagra9**
#295 

image

### CODE REVIEW

**Review by shalithasuranga — CHANGES_REQUESTED** [review]
Hello @skushagra9  Thanks for sending this PR. Could you please update these modifications as follows:

- Remove the `credits` prop -- We typically link the original repo, so no need to add the organization as credits. 
- Please add only templates, the repos you added are not valid Neutralinojs templates

We can merge this PR once you update it according to the above points. Let me know if you have questions :) Thanks

**Comment by skushagra9** [comment]
Sure, I will update it , thanks

**Comment by skushagra9** [comment]
@shalithasuranga , I have added the changes, doesn't it lookalike  now ?
image

**Review by shalithasuranga — APPROVED** [review]
Thanks so much @skushagra9, this is finally merged. 

Note: I'll create separate sections for titles and misc resources later

**Pull request merged**
