### PR TITLE
Solved Issue: #239

### PR DESCRIPTION
**Pull request by devanshkansagra**
I've added a new "Tools and Templates" section, featuring various templates like Neutralinojs-Vue, Neutralinojs-React, and more. I've also created a component called template.js to showcase them.

While I couldn't find specific logos, I've used Neutralinojs logos temporarily. I apologize for any inconvenience.

This is my first open-source contribution, and I'm eager for feedback and future challenges!

### CODE REVIEW

**Comment by devanshkansagra** [comment]
I also apologize for the typo errors in the solution

**Comment by shalithasuranga** [comment]
Hello @devanshkansagra thanks for sending this PR. Could you please remove archived and inactive repos (Add better ones like https://github.com/codezri/neutralinojs-react) from the list and make the entire list as a simple unordered list ?
I meant that we can create a simple list like https://github.com/achou11/awesome-neutralino

Thanks :tada:

**Comment by devanshkansagra** [comment]
Can you tell me what tools and templates you want to add in this section? So that I can work accordingly
Also provide me the links of the github repository of those tools respectively

**Comment by devanshkansagra** [comment]
And as you said before the unordered list like this https://github.com/neutralinojs/neutralinojs.github.io/assets/125076549/01ccbcae-e1de-4755-8dd0-7b6c6bf50484
you want? Just asking for the reference

**Comment by shalithasuranga** [comment]
Hello @devanshkansagra, I think you can add some popular, updated repos, like the React template, minimal template etc. Also, I think you can add a few at this point (maybe two or three) since you typically focus on implementing the new tools and templates React page. Later, contributors will add more list items there..

Thanks :tada:

**Comment by devanshkansagra** [comment]
Hey @shalithasuranga, Can you please review my pull request #288 so that if there are any tasks or any changes to be made, I will Happy to contribute to this issue

**Comment by shalithasuranga** [comment]
I am closing this in favor of #288 .. Thanks

**Pull request closed without merging**
