### PR TITLE
Changed the UI of the main page index.js 

### PR DESCRIPTION
**Pull request by harshit-dugar**
I have centered the heading of the build part and made thr paragraph arranged properly with the section.

### CODE REVIEW

**Comment by pathange-s** [comment]
Centering it looks more aesthetic. Don't you think so? Center it, we can go for a merge. Great job !
image

**Comment by harshit-dugar** [comment]
Ok going to make this change

**Comment by harshit-dugar** [comment]
@pathange-s I have done it please take a look.

**Comment by harshit-dugar** [comment]
@pathange-s is it ok now

**Comment by pathange-s** [comment]
Great!

**Comment by harshit-dugar** [comment]
Is it merged ?

**Comment by harshit-dugar** [comment]
@pathange-s what about the merge.
Also I have made a pr on the main repo

**Review by shalithasuranga — APPROVED** [review]
Looks great! Thanks so much :tada:

**Pull request merged**
