### PR TITLE
Update `filesystem.getStats` return Object to include `createdAt` and `modifiedAt`

### PR DESCRIPTION
**Pull request by HappyStriker**
This change becomes vital, if the pull request [Update filesystem.getStats(path) to fetch last modified time](https://github.com/neutralinojs/neutralinojs/pull/877) gets merged.

### CODE REVIEW

**Comment by pathange-s** [comment]
Great ! Also, todo includes: updating code for WIN32, and test suite for the updated function.

**Comment by shalithasuranga** [comment]
Great! let's merge this one after releasing the next framework version. Thanks for sending this :tada:

**Review by shalithasuranga — APPROVED** [review]
Thank you very much for the contribution :tada:

**Comment by shalithasuranga** [comment]
Just merged this one but will comment out these until we release the next version :D

**Pull request merged**
